// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDelMKLNy00BhwxYSYkhE_-LcUoStCrP4M',
    appId: '1:827541937089:web:7b6a15bd3a1fa6d79e6d40',
    messagingSenderId: '827541937089',
    projectId: 'aziza-8a007',
    authDomain: 'aziza-8a007.firebaseapp.com',
    storageBucket: 'aziza-8a007.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-0qV8Iqb15lmOP1wUshFr5wyl610N8mQ',
    appId: '1:827541937089:android:9680a191659506d89e6d40',
    messagingSenderId: '827541937089',
    projectId: 'aziza-8a007',
    storageBucket: 'aziza-8a007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-bBliF2dR8kNdGsZsmjgxtcAtNvu0vKw',
    appId: '1:827541937089:ios:d25b3fae69c2bc2c9e6d40',
    messagingSenderId: '827541937089',
    projectId: 'aziza-8a007',
    storageBucket: 'aziza-8a007.appspot.com',
    iosBundleId: 'com.example.firbase',
  );
}
